# Generated by Django 3.2 on 2021-04-17 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golftrekker', '0004_auto_20210414_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_confirm',
        ),
    ]
