# Generated by Django 3.2 on 2021-04-20 21:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('golftrekker', '0007_rename_instruction_instruction_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction_choice',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 4, 20, 21, 40, 18, 236586, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
